on: [push, pull_request]

jobs:
  test_notify:
    runs-on: self-hosted
    name: Test the action
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deployment Started
        run: exit 0
      - name: select working directory
        run: cd .
      - name: install node packages
        run: npm install
      - name: Sending notification to slack 
        uses: ./ 
        if: always()
        with:
          event: ${{ toJson(github.event) }}
          job-status: started
          service-name: Backend
          env-name: Staging
          slack-bot-token: ${{ secrets.SLACK_TOKEN }}
          channel: githubactionspublic
  test_ko:
    runs-on: self-hosted
    name: Test the action on failure
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deployment ended
        run: exit 0
      - name: select working directory
        run: cd .
      - name: install node packages
        run: npm install
      - name: Sending notification to slack 
        uses: ./
        if: always()
        with:
            event: ${{ toJson(github.event) }}
            job-status: ended
            service-name: Backend
            env-name: Staging
            slack-bot-token: ${{ secrets.SLACK_TOKEN }}
            channel: githubactionspublic
