on: [push, pull_request]

jobs:
  test_notify:
    runs-on: ubuntu-latest
    name: Test the action
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy Started
        run: exit 0
      - name: install node packages
        run: npm install
      - name: Action
        uses: ./ 
        if: always()
        with:
          event: ${{ toJson(github.event) }}
          job-status: ${{ job.status }}
          slack-bot-token: ${{ secrets.SLACK_TOKEN }}
          channel: githubactionspublic
  test_ko:
    runs-on: ubuntu-latest
    name: Test the action on failure
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deployed ended
        run: exit 0
      - name: install node packages
        run: npm install
      - name: Action
        uses: ./
        if: always()
        with:
            event: ${{ toJson(github.event) }}
            job-status: ${{ job.status }}
            slack-bot-token: ${{ secrets.SLACK_TOKEN }}
            channel: githubactionspublic
